In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline


## create data set

In [2]:
from sklearn.datasets import make_classification

In [3]:
X,y=make_classification(n_samples=1000,n_features=10,n_informative=3,n_classes=3,random_state=42)

In [4]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0    0.771533 -1.474336  2.196646 -0.678992  0.767479 -1.226179 -0.237566   
1    1.858383 -3.680880  0.227496 -3.818368  0.635968  1.609521 -0.153135   
2   -0.987248  1.539168  0.585904  1.185281 -0.736770 -1.406815  0.684783   
3   -1.022420  1.381787  2.015275  0.861434  1.290644 -1.889649  1.009138   
4   -0.131161 -2.079008  1.483744  1.636858 -0.734811 -0.640154  2.666422   
..        ...       ...       ...       ...       ...       ...       ...   
995  0.982677 -1.908917 -0.385673 -2.565989  0.434503 -1.334611 -0.060318   
996 -1.144949  1.434090 -0.459657  0.358606 -1.079842  0.918915  1.339638   
997 -1.227082  1.656028  0.472630  1.718125 -1.366858  0.018017  1.131626   
998  1.285276 -0.297152 -0.671721 -1.843337 -1.254161 -0.276889 -2.913304   
999 -0.754280  0.885161 -1.672894  0.652953  0.404213 -0.249072  0.904253   

            7         8         9  
0    0.681743  1.089962  0.962503  
1   -0.474178  1.341139 -0.771772  
2   -0.322028 -1.451034  1.325432  
3    0.363116 -1.844238  0.311110  
4   -1.085748 -0.892851  0.029796  
..        ...       ...       ...  
995  1.040062  0.433730 -0.739771  
996  1.193113 -2.473007  1.021515  
997 -0.863494 -1.839323 -0.031203  
998 -1.315441  2.854465  1.309444  
999 -2.036221 -1.439896  0.047493  

[1000 rows x 10 columns]

In [6]:
y

array([1, 2, 1, 1, 2, 1, 1, 0, 2, 2, 2, 0, 1, 0, 2, 1, 2, 1, 0, 1, 1, 1,
       2, 2, 1, 2, 2, 0, 1, 2, 0, 1, 0, 2, 0, 1, 0, 0, 2, 0, 1, 0, 2, 1,
       2, 0, 2, 0, 2, 0, 0, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0, 1, 2,
       0, 2, 2, 1, 0, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0,
       0, 1, 1, 2, 1, 0, 1, 2, 0, 2, 0, 0, 2, 1, 0, 2, 0, 2, 2, 0, 2, 0,
       0, 0, 0, 2, 1, 2, 1, 0, 2, 0, 0, 2, 1, 0, 2, 1, 0, 0, 2, 2, 0, 0,
       0, 2, 1, 2, 2, 0, 2, 0, 1, 2, 1, 2, 1, 1, 2, 0, 0, 1, 0, 2, 0, 0,
       0, 1, 1, 2, 1, 2, 2, 0, 0, 0, 1, 1, 0, 2, 1, 2, 2, 2, 1, 1, 0, 2,
       1, 0, 2, 1, 2, 1, 2, 0, 1, 1, 0, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2,
       1, 2, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0,
       2, 0, 1, 1, 2, 1, 2, 2, 2, 2, 0, 1, 0, 0, 0, 0, 2, 2, 2, 1, 1, 1,
       0, 2, 0, 0, 1, 0, 2, 0, 1, 2, 2, 2, 1, 2, 1, 0, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 0, 0, 0, 2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 0, 0, 2, 2,
       2, 1, 1, 1, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 1,

## train test split

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

## model training

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
log_reg=LogisticRegression(multi_class='ovr')
log_reg.fit(X_train,y_train)

LogisticRegression(multi_class='ovr')

In [15]:
y_pred=log_reg.predict(X_test)

In [16]:
y_pred

array([2, 0, 1, 2, 0, 1, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 0, 0, 0,
       2, 0, 1, 0, 2, 1, 0, 2, 2, 0, 1, 0, 0, 2, 2, 2, 1, 0, 0, 1, 2, 0,
       1, 2, 1, 0, 1, 1, 2, 0, 1, 0, 2, 2, 2, 2, 1, 2, 0, 2, 2, 2, 1, 1,
       0, 1, 0, 1, 0, 2, 2, 0, 0, 0, 2, 1, 1, 2, 2, 0, 2, 1, 0, 1, 1, 2,
       1, 1, 2, 2, 1, 2, 2, 2, 1, 0, 0, 0, 0, 2, 1, 0, 2, 1, 1, 0, 0, 2,
       0, 1, 2, 0, 0, 0, 1, 1, 2, 2, 1, 0, 0, 1, 2, 0, 0, 1, 0, 2, 1, 0,
       2, 2, 2, 0, 0, 1, 2, 1, 2, 1, 2, 1, 2, 2, 2, 0, 0, 1, 2, 0, 0, 2,
       1, 0, 0, 0, 2, 0, 0, 0, 2, 2, 2, 2, 2, 1, 2, 1, 0, 2, 1, 0, 0, 2,
       0, 1, 1, 2, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 2, 1, 2, 2, 1, 2,
       0, 1, 2, 2, 1, 1, 0, 2, 1, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 2, 2, 2, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 2, 1, 0, 1, 2, 0, 0, 2,
       0, 2, 0, 0, 2, 2, 0, 2, 2, 0, 1, 2, 2, 0, 1, 1, 0, 1, 2, 0, 2, 2,
       0, 0, 0, 2, 1, 2, 0, 2, 2, 2, 0, 2, 0, 2, 2, 0, 0, 1, 0, 2, 2, 2,
       0, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 2, 0, 1])

In [17]:
log_reg.predict_proba(X_test)

array([[9.22522618e-03, 2.44034837e-01, 7.46739937e-01],
       [4.89544732e-01, 2.45683892e-01, 2.64771376e-01],
       [3.54058728e-01, 5.90982894e-01, 5.49583777e-02],
       [3.61503652e-02, 1.82525799e-01, 7.81323836e-01],
       [4.01755652e-01, 3.69771801e-01, 2.28472547e-01],
       [3.83231093e-01, 5.21315790e-01, 9.54531172e-02],
       [2.80650254e-01, 2.18835528e-01, 5.00514218e-01],
       [6.86748730e-01, 3.10472372e-01, 2.77889720e-03],
       [5.72702266e-01, 4.24212176e-01, 3.08555794e-03],
       [2.69546511e-02, 1.49732219e-01, 8.23313130e-01],
       [7.81732426e-02, 2.40515273e-01, 6.81311484e-01],
       [1.25869742e-02, 1.72900197e-01, 8.14512828e-01],
       [4.99079983e-02, 1.76510922e-01, 7.73581080e-01],
       [3.95794074e-02, 3.56708621e-01, 6.03711972e-01],
       [2.01209577e-02, 2.98735180e-01, 6.81143862e-01],
       [7.35993162e-03, 2.18049789e-01, 7.74590279e-01],
       [2.71868855e-02, 2.81421225e-01, 6.91391890e-01],
       [2.36865580e-01, 4.86991

## performance metrics

In [18]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [19]:
score=accuracy_score(y_test,y_pred)
print(score)
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.68
[[79 16  8]
 [31 38 27]
 [ 3 11 87]]
              precision    recall  f1-score   support

           0       0.70      0.77      0.73       103
           1       0.58      0.40      0.47        96
           2       0.71      0.86      0.78       101

    accuracy                           0.68       300
   macro avg       0.67      0.67      0.66       300
weighted avg       0.67      0.68      0.66       300



## Hyperparameter Tuning

In [20]:
model=LogisticRegression()
penalty=['l1', 'l2', 'elasticnet']
c_values=[100,10,1.0,0.1,0.01]
solver=['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']

In [21]:
params=dict(penalty=penalty,C=c_values,solver=solver)

### grid search CV

In [22]:
from sklearn.model_selection import GridSearchCV, StratifiedKFold

In [23]:
cv=StratifiedKFold()

In [24]:
grid=GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv,n_jobs=-1)

In [25]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [26]:
grid.fit(X_train,y_train)

c:\Users\prasa\anaconda3\Lib\site-packages\sklearn\svm\_base.py:1237: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\prasa\anaconda3\Lib\site-packages\sklearn\svm\_base.py:1237: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\prasa\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\prasa\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\prasa\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\prasa\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached 

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [27]:
grid.best_params_

{'C': 0.01, 'penalty': 'l1', 'solver': 'saga'}

In [28]:
grid.best_score_

0.6528571428571428

In [29]:
y_pred=grid.predict(X_test)

In [30]:
score=accuracy_score(y_test,y_pred)
print(score)
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.7033333333333334
[[78 17  8]
 [28 43 25]
 [ 3  8 90]]
              precision    recall  f1-score   support

           0       0.72      0.76      0.74       103
           1       0.63      0.45      0.52        96
           2       0.73      0.89      0.80       101

    accuracy                           0.70       300
   macro avg       0.69      0.70      0.69       300
weighted avg       0.69      0.70      0.69       300



### Randomized Search CV

In [31]:
from sklearn.model_selection import RandomizedSearchCV

In [32]:
model=LogisticRegression()

In [33]:
randomcv=RandomizedSearchCV(estimator=model,param_distributions=params,cv=5,scoring='accuracy')

In [34]:
randomcv.fit(X_train,y_train)

c:\Users\prasa\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning: 
20 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\prasa\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\prasa\anaconda3\Lib\site-packages\sklearn\base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\prasa\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1172, in fit
    solver = _c

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [35]:
randomcv.best_params_

{'solver': 'sag', 'penalty': 'l2', 'C': 0.01}

In [36]:
randomcv.best_score_

0.63

In [37]:
y_pred=randomcv.predict(X_test)

In [38]:
score=accuracy_score(y_test,y_pred)
print(score)
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.7
[[76 20  7]
 [25 47 24]
 [ 3 11 87]]
              precision    recall  f1-score   support

           0       0.73      0.74      0.73       103
           1       0.60      0.49      0.54        96
           2       0.74      0.86      0.79       101

    accuracy                           0.70       300
   macro avg       0.69      0.70      0.69       300
weighted avg       0.69      0.70      0.69       300

